backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"   # Carpeta donde suben imágenes
public_folder: "/assets/images/uploads"

collections:
  - name: "home"
    label: "Página Principal"
    files:
      - label: "Contenido Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Título Hero", name: "hero_title", widget: "string" }
          - { label: "Texto Hero", name: "hero_text", widget: "text" }
          - { label: "CTA Texto", name: "cta_text", widget: "string" }

  - name: "proyectos"
    label: "Proyectos"
    folder: "content/proyectos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
