backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  # Página principal (archivo único)
  - name: "home"
    label: "Home"
    files:
      - file: "content/home.md"
        label: "Página principal"
        name: "home"
        fields:
          - { label: "Título principal", name: "title", widget: "string" }
          - { label: "Descripción hero", name: "description", widget: "text" }
          - { label: "CTA texto", name: "cta_text", widget: "string" }
          - { label: "CTA link", name: "cta_link", widget: "string", default: "#contacto" }

  # Servicios (archivo único)
  - name: "servicios"
    label: "Servicios"
    files:
      - file: "content/servicios.md"
        label: "Sección Servicios"
        name: "servicios"
        fields:
          - { label: "Título sección", name: "title", widget: "string" }
          - { label: "Descripción sección", name: "description", widget: "text" }
          - label: "Lista de servicios"
            name: "items"
            widget: "list"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Descripción", name: "text", widget: "text" }
              - { label: "Icono (SVG)", name: "icon", widget: "text" }

  # Proyectos (carpeta, múltiples archivos)
  - name: "proyectos"
    label: "Proyectos"
    folder: "content/proyectos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Tag", name: "tag", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }

  # FAQ (archivo único)
  - name: "faq"
    label: "FAQ"
    files:
      - file: "content/faq.md"
        label: "Sección FAQ"
        name: "faq"
        fields:
          - { label: "Título sección", name: "title", widget: "string" }
          - label: "Preguntas"
            name: "items"
            widget: "list"
            fields:
              - { label: "Pregunta", name: "q", widget: "string" }
              - { label: "Respuesta", name: "a", widget: "text" }

  # Contacto (archivo único)
  - name: "contacto"
    label: "Contacto"
    files:
      - file: "content/contacto.md"
        label: "Sección Contacto"
        name: "contacto"
        fields:
          - { label: "Título sección", name: "title", widget: "string" }
          - { label: "Descripción", name: "description", widget: "text" }
          - { label: "Email destino", name: "email", widget: "string" }
